/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.buburgowes.view.customer;

/**
 * @author BuburGowes
 */

import com.buburgowes.controller.CustomerController;
import com.buburgowes.model.Customer;

import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

import static java.awt.EventQueue.invokeLater;

public class CustomerMain extends javax.swing.JFrame {

    private static Customer currentUser;
    /**
     * Creates new form CustomerMain
     */
    private final CustomerController buburGowes = new CustomerController();

    public CustomerMain(Customer currentUser) {

        if (buburGowes.checkDBConnection(this)) {
            this.setTitle("Bubur Gowes - Customer");
            buburGowes.currentUser = currentUser;
            initComponents();
            tfOrderFullname.setEditable(false);
            tfOrderNoTelp.setEditable(false);
        } else {
            System.exit(0);
        }

        buburGowes.loadProductData();

        // Membuat tabel order

        tabelOrder.setModel(buburGowes.tabelModel);

        // Membuat judul kolom tabel order center

        TableCellRenderer rendererFromHeader = tabelOrder.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);

        // Buat kolom No bisa resize
        TableColumnModel columnModel = tabelOrder.getColumnModel();
        columnModel.getColumn(0).setResizable(true);

        // Set jSpinner jumlah pesanan minimum 1 dan maksimum 10
        jSpinnerBubur1.setModel(new SpinnerNumberModel(0, 0, 10, 1));
        jSpinnerBubur2.setModel(new SpinnerNumberModel(0, 0, 10, 1));
        jSpinnerBubur3.setModel(new SpinnerNumberModel(0, 0, 10, 1));

        tfOrderFullname.setText(currentUser.getUser_fullName());
        tfOrderNoTelp.setText(currentUser.getUser_phoneNumber());
        tfOrderAlamat.setText(currentUser.getUser_address());

        buburGowes.loadOrderTabel();

        /*
        TableColumnModel columnModel = tabelOrder.getColumnModel();
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();

        columnModel.getColumn(0).setMinWidth(320);
        columnModel.getColumn(1).setMinWidth(200);
        columnModel.getColumn(2).setMinWidth(320);

        cellRenderer.setHorizontalAlignment(CENTER);
        columnModel.getColumn(1).setCellRenderer(cellRenderer);
        columnModel.getColumn(2).setCellRenderer(cellRenderer);
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_edit = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jPanelNavBar = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelToLogin = new javax.swing.JPanel();
        jLabelUserState = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabelHome1 = new javax.swing.JLabel();
        jLabelHome2 = new javax.swing.JLabel();
        jButtonHomeToMenu = new javax.swing.JButton();
        jPanelMainIcon = new javax.swing.JPanel();
        jLabelMainIcon = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jPanelBubur1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabelGambarBubur1 = new javax.swing.JLabel();
        jLabelBubur1 = new javax.swing.JLabel();
        jLabelHarga1 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLanelStar1 = new javax.swing.JLabel();
        jLabelRating1 = new javax.swing.JLabel();
        jPanelKeranjang1 = new javax.swing.JPanel();
        jLabelKeranjang1 = new javax.swing.JLabel();
        jPanelBubur2 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabelGambarBubur2 = new javax.swing.JLabel();
        jLabelBubur2 = new javax.swing.JLabel();
        jLabelHarga2 = new javax.swing.JLabel();
        jLanelStar2 = new javax.swing.JLabel();
        jLabelRating2 = new javax.swing.JLabel();
        jPanelKeranjang2 = new javax.swing.JPanel();
        jLabelKeranjang2 = new javax.swing.JLabel();
        jPanelBubur3 = new javax.swing.JPanel();
        jLabelGambarBubur3 = new javax.swing.JLabel();
        jLabelBubur3 = new javax.swing.JLabel();
        jLabelHarga3 = new javax.swing.JLabel();
        jLanelStar3 = new javax.swing.JLabel();
        jLabelRating3 = new javax.swing.JLabel();
        jPanelKeranjang3 = new javax.swing.JPanel();
        jLabelKeranjang3 = new javax.swing.JLabel();
        jPanelOrder = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        tfOrderFullname = new javax.swing.JTextField();
        tfOrderNoTelp = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelOrder = new javax.swing.JTable();
        jSpinnerBubur1 = new javax.swing.JSpinner();
        jSpinnerBubur2 = new javax.swing.JSpinner();
        jSpinnerBubur3 = new javax.swing.JSpinner();
        jLabelOrderBubur1 = new javax.swing.JLabel();
        jLabelOrderBubur2 = new javax.swing.JLabel();
        jLabelOrderBubur3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tfOrderAlamat = new javax.swing.JTextArea();
        jPanelAboutUs = new javax.swing.JPanel();

        jLabel12.setFont(new java.awt.Font("Poppins SemiBold", 2, 36)); // NOI18N
        jLabel12.setText("Abis gowes belum sarapan ?");

        btn_edit.setBackground(new java.awt.Color(97, 151, 63));
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(235, 233, 176));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNavBar.setBackground(new java.awt.Color(217, 204, 100));

        jPanel13.setBackground(new java.awt.Color(97, 151, 63));
        jPanel13.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel13AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menu");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(97, 151, 63));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Order");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(97, 151, 63));
        jPanel15.setPreferredSize(new java.awt.Dimension(90, 31));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("About Us");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(20, 20, 20))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(97, 151, 63));
        jPanel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel16MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Home");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelToLogin.setBackground(new java.awt.Color(97, 151, 63));
        jPanelToLogin.setPreferredSize(new java.awt.Dimension(84, 31));
        jPanelToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelToLoginMouseClicked(evt);
            }
        });

        jLabelUserState.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabelUserState.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserState.setText("Logout");
        jLabelUserState.setToolTipText("");

        javax.swing.GroupLayout jPanelToLoginLayout = new javax.swing.GroupLayout(jPanelToLogin);
        jPanelToLogin.setLayout(jPanelToLoginLayout);
        jPanelToLoginLayout.setHorizontalGroup(
            jPanelToLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelToLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserState, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelToLoginLayout.setVerticalGroup(
            jPanelToLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserState)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/nav_logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanelNavBarLayout = new javax.swing.GroupLayout(jPanelNavBar);
        jPanelNavBar.setLayout(jPanelNavBarLayout);
        jPanelNavBarLayout.setHorizontalGroup(
            jPanelNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavBarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jPanelToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelNavBarLayout.setVerticalGroup(
            jPanelNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNavBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(jPanelNavBarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMain.add(jPanelNavBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 110));

        jTabbedPane1.setBackground(new java.awt.Color(235, 233, 176));

        jPanelHome.setBackground(new java.awt.Color(235, 233, 176));

        jLabelHome1.setFont(new java.awt.Font("Poppins SemiBold", 2, 36)); // NOI18N
        jLabelHome1.setText("Abis gowes belum sarapan ?");

        jLabelHome2.setFont(new java.awt.Font("Freestyle Script", 0, 101)); // NOI18N
        jLabelHome2.setText("Pesan Sekarang");

        jButtonHomeToMenu.setBackground(new java.awt.Color(97, 151, 63));
        jButtonHomeToMenu.setFont(new java.awt.Font("Poppins SemiBold", 2, 20)); // NOI18N
        jButtonHomeToMenu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHomeToMenu.setText("Lihat Menu");
        jButtonHomeToMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomeToMenuMouseClicked(evt);
            }
        });
        jButtonHomeToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeToMenuActionPerformed(evt);
            }
        });

        jPanelMainIcon.setBackground(new java.awt.Color(235, 233, 176));

        javax.swing.GroupLayout jPanelMainIconLayout = new javax.swing.GroupLayout(jPanelMainIcon);
        jPanelMainIcon.setLayout(jPanelMainIconLayout);
        jPanelMainIconLayout.setHorizontalGroup(
            jPanelMainIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );
        jPanelMainIconLayout.setVerticalGroup(
            jPanelMainIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );

        jLabelMainIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMainIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/mainbubur.png"))); // NOI18N

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButtonHomeToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHome2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHome1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanelMainIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(jLabelMainIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabelHome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHome2)
                        .addGap(20, 20, 20)
                        .addComponent(jButtonHomeToMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelMainIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelMainIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanelHome);

        jPanelMenu.setBackground(new java.awt.Color(235, 233, 176));

        jPanelBubur1.setBackground(new java.awt.Color(255, 254, 220));

        jPanel12.setBackground(new java.awt.Color(255, 254, 220));

        jLabelGambarBubur1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/bubur1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelGambarBubur1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGambarBubur1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelBubur1.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabelBubur1.setText("Bubur Polos");

        jLabelHarga1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabelHarga1.setText("Rp 7.000,00");

        jPanel19.setBackground(new java.awt.Color(255, 254, 220));

        jLanelStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/stars.png"))); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLanelStar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLanelStar1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelRating1.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelRating1.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRating1.setText("4.4");

        jPanelKeranjang1.setBackground(new java.awt.Color(97, 151, 63));
        jPanelKeranjang1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelKeranjang1MouseClicked(evt);
            }
        });

        jLabelKeranjang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/cart.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeranjang1Layout = new javax.swing.GroupLayout(jPanelKeranjang1);
        jPanelKeranjang1.setLayout(jPanelKeranjang1Layout);
        jPanelKeranjang1Layout.setHorizontalGroup(
            jPanelKeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeranjang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKeranjang1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelKeranjang1Layout.setVerticalGroup(
            jPanelKeranjang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeranjang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKeranjang1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBubur1Layout = new javax.swing.GroupLayout(jPanelBubur1);
        jPanelBubur1.setLayout(jPanelBubur1Layout);
        jPanelBubur1Layout.setHorizontalGroup(
            jPanelBubur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBubur1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelBubur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBubur1Layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRating1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelKeranjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanelBubur1Layout.createSequentialGroup()
                        .addGroup(jPanelBubur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBubur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelBubur1Layout.createSequentialGroup()
                                    .addComponent(jLabelHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(121, 121, 121)))
                            .addComponent(jLabelBubur1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        jPanelBubur1Layout.setVerticalGroup(
            jPanelBubur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBubur1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelBubur1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBubur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBubur1Layout.createSequentialGroup()
                        .addComponent(jLabelHarga1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBubur1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelRating1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanelKeranjang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanelBubur2.setBackground(new java.awt.Color(255, 254, 220));

        jPanel18.setBackground(new java.awt.Color(255, 254, 220));

        jLabelGambarBubur2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/bubur2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGambarBubur2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGambarBubur2)
                .addGap(98, 98, 98))
        );

        jLabelBubur2.setFont(new java.awt.Font("Poppins SemiBold", 0, 24)); // NOI18N
        jLabelBubur2.setText("Bubur Ayam");

        jLabelHarga2.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabelHarga2.setText("Rp 12.000,00");

        jLanelStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/stars.png"))); // NOI18N

        jLabelRating2.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelRating2.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRating2.setText("4.9");

        jPanelKeranjang2.setBackground(new java.awt.Color(97, 151, 63));

        jLabelKeranjang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/cart.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeranjang2Layout = new javax.swing.GroupLayout(jPanelKeranjang2);
        jPanelKeranjang2.setLayout(jPanelKeranjang2Layout);
        jPanelKeranjang2Layout.setHorizontalGroup(
            jPanelKeranjang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeranjang2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKeranjang2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelKeranjang2Layout.setVerticalGroup(
            jPanelKeranjang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeranjang2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKeranjang2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBubur2Layout = new javax.swing.GroupLayout(jPanelBubur2);
        jPanelBubur2.setLayout(jPanelBubur2Layout);
        jPanelBubur2Layout.setHorizontalGroup(
            jPanelBubur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBubur2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 269, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBubur2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelBubur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBubur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelBubur2, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(jLabelHarga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelBubur2Layout.createSequentialGroup()
                        .addComponent(jLanelStar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRating2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelKeranjang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanelBubur2Layout.setVerticalGroup(
            jPanelBubur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBubur2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelBubur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelKeranjang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBubur2Layout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBubur2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHarga2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBubur2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLanelStar2)
                            .addComponent(jLabelRating2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBubur3.setBackground(new java.awt.Color(255, 254, 220));

        jLabelGambarBubur3.setBackground(new java.awt.Color(255, 254, 220));
        jLabelGambarBubur3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/bubur3.png"))); // NOI18N

        jLabelBubur3.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
        jLabelBubur3.setText("Bubur Ayam Ati Ampela");

        jLabelHarga3.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabelHarga3.setText("Rp 15.000,00");

        jLanelStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/stars.png"))); // NOI18N

        jLabelRating3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabelRating3.setForeground(new java.awt.Color(102, 102, 102));
        jLabelRating3.setText("4.6");

        jPanelKeranjang3.setBackground(new java.awt.Color(97, 151, 63));

        jLabelKeranjang3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/buburgowes/assets/images/cart.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKeranjang3Layout = new javax.swing.GroupLayout(jPanelKeranjang3);
        jPanelKeranjang3.setLayout(jPanelKeranjang3Layout);
        jPanelKeranjang3Layout.setHorizontalGroup(
            jPanelKeranjang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeranjang3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKeranjang3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelKeranjang3Layout.setVerticalGroup(
            jPanelKeranjang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKeranjang3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKeranjang3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBubur3Layout = new javax.swing.GroupLayout(jPanelBubur3);
        jPanelBubur3.setLayout(jPanelBubur3Layout);
        jPanelBubur3Layout.setHorizontalGroup(
            jPanelBubur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBubur3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelBubur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGambarBubur3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBubur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelBubur3, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelBubur3Layout.createSequentialGroup()
                            .addGroup(jPanelBubur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelBubur3Layout.createSequentialGroup()
                                    .addComponent(jLanelStar3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelRating3))
                                .addComponent(jLabelHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelKeranjang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelBubur3Layout.setVerticalGroup(
            jPanelBubur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBubur3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBubur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelKeranjang3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBubur3Layout.createSequentialGroup()
                        .addComponent(jLabelGambarBubur3)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelBubur3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHarga3)
                        .addGap(6, 6, 6)
                        .addGroup(jPanelBubur3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLanelStar3)
                            .addComponent(jLabelRating3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPanelBubur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelBubur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBubur3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelBubur2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBubur3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBubur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menu", jPanelMenu);

        jPanelOrder.setBackground(new java.awt.Color(235, 233, 176));

        jPanel23.setBackground(new java.awt.Color(255, 254, 220));

        jLabel31.setText("Nama");

        jLabel32.setText("Alamat");

        jLabel33.setText("Pesanan");

        jLabel34.setText("Jumlah");

        tfOrderFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOrderFullnameActionPerformed(evt);
            }
        });

        tfOrderNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfOrderNoTelpActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(97, 151, 63));
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Batalkan");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_reset.setBackground(new java.awt.Color(97, 151, 63));
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_tambah.setBackground(new java.awt.Color(97, 151, 63));
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("Pesan");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        jLabel36.setText("No Telp");

        tabelOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Faiz", "0987654321", "Bandung", "Bubur Polos", "2", "14000"},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "No Telp", "Alamat", "Pesanan", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelOrder.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelOrder);

        jSpinnerBubur1.setName(""); // NOI18N
        jSpinnerBubur1.setRequestFocusEnabled(false);

        jLabelOrderBubur1.setText("Bubur Polos");

        jLabelOrderBubur2.setText("Bubur Ayam");

        jLabelOrderBubur3.setText("Bubur Ayam Ati Ampela");

        tfOrderAlamat.setColumns(20);
        tfOrderAlamat.setRows(5);
        jScrollPane3.setViewportView(tfOrderAlamat);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel36)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfOrderNoTelp)
                            .addComponent(tfOrderFullname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelOrderBubur3)
                                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabelOrderBubur1)
                                                .addComponent(jLabelOrderBubur2)))
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSpinnerBubur3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jSpinnerBubur2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jSpinnerBubur1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(btn_hapus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_reset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_tambah)))
                                .addGap(45, 45, 45)))))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(tfOrderFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(tfOrderNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jSpinnerBubur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerBubur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerBubur3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabelOrderBubur1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOrderBubur2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelOrderBubur3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_hapus)
                            .addComponent(btn_reset)
                            .addComponent(btn_tambah))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanelOrderLayout = new javax.swing.GroupLayout(jPanelOrder);
        jPanelOrder.setLayout(jPanelOrderLayout);
        jPanelOrderLayout.setHorizontalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelOrderLayout.setVerticalGroup(
            jPanelOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrderLayout.createSequentialGroup()
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Order", jPanelOrder);

        jPanelAboutUs.setBackground(new java.awt.Color(235, 233, 176));

        javax.swing.GroupLayout jPanelAboutUsLayout = new javax.swing.GroupLayout(jPanelAboutUs);
        jPanelAboutUs.setLayout(jPanelAboutUsLayout);
        jPanelAboutUsLayout.setHorizontalGroup(
            jPanelAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jPanelAboutUsLayout.setVerticalGroup(
            jPanelAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About Us", jPanelAboutUs);

        jPanelMain.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1050, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel16MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel16MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jPanel14MouseClicked

    private void jPanel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jPanel15MouseClicked

    private void jPanelToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelToLoginMouseClicked
        // TODO add your handling code here:
        jLabelUserState.setText("Login");
        buburGowes.goToLogin(this);
    }//GEN-LAST:event_jPanelToLoginMouseClicked

    private void jPanel13AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel13AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13AncestorAdded

    private void tfOrderNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOrderNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOrderNoTelpActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:

        String nama = tfOrderFullname.getText();
        String noTelp = tfOrderNoTelp.getText();
        String alamat = tfOrderAlamat.getText();

        //variabel jumlah setiap pesanan
        int jumlahBubur1 = (int) jSpinnerBubur1.getValue();
        int jumlahBubur2 = (int) jSpinnerBubur2.getValue();
        int jumlahBubur3 = (int) jSpinnerBubur3.getValue();

        // varible for current date
        /*Date date = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        String strDate = formatter.format(date);*/

        buburGowes.executeOrder(this, nama, noTelp, alamat, jumlahBubur1, jumlahBubur2, jumlahBubur3);

        // Clear all spinner after order is done
        jSpinnerBubur1.setValue(0);
        jSpinnerBubur2.setValue(0);
        jSpinnerBubur3.setValue(0);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        jSpinnerBubur1.setValue(0);
        jSpinnerBubur2.setValue(0);
        jSpinnerBubur3.setValue(0);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tfOrderFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfOrderFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfOrderFullnameActionPerformed

    private void jButtonHomeToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeToMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomeToMenuActionPerformed

    private void jButtonHomeToMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeToMenuMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButtonHomeToMenuMouseClicked

    private void jPanelKeranjang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKeranjang1MouseClicked
        // TODO add your handling code here:
        if (jSpinnerBubur1.getValue().equals(0)) jSpinnerBubur1.setValue(1);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jPanelKeranjang1MouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        // remove selected row from the database
        int row = tabelOrder.getSelectedRow();

        if (row != -1) {
            try {
                String id = tabelOrder.getValueAt(row, 0).toString();

                buburGowes.cancelOrderData(
                        this,
                        id
                );

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        invokeLater(() -> {
            new CustomerMain(currentUser).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonHomeToMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBubur1;
    private javax.swing.JLabel jLabelBubur2;
    private javax.swing.JLabel jLabelBubur3;
    private javax.swing.JLabel jLabelGambarBubur1;
    private javax.swing.JLabel jLabelGambarBubur2;
    private javax.swing.JLabel jLabelGambarBubur3;
    private javax.swing.JLabel jLabelHarga1;
    private javax.swing.JLabel jLabelHarga2;
    private javax.swing.JLabel jLabelHarga3;
    private javax.swing.JLabel jLabelHome1;
    private javax.swing.JLabel jLabelHome2;
    private javax.swing.JLabel jLabelKeranjang1;
    private javax.swing.JLabel jLabelKeranjang2;
    private javax.swing.JLabel jLabelKeranjang3;
    private javax.swing.JLabel jLabelMainIcon;
    private javax.swing.JLabel jLabelOrderBubur1;
    private javax.swing.JLabel jLabelOrderBubur2;
    private javax.swing.JLabel jLabelOrderBubur3;
    private javax.swing.JLabel jLabelRating1;
    private javax.swing.JLabel jLabelRating2;
    private javax.swing.JLabel jLabelRating3;
    private javax.swing.JLabel jLabelUserState;
    private javax.swing.JLabel jLanelStar1;
    private javax.swing.JLabel jLanelStar2;
    private javax.swing.JLabel jLanelStar3;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanelAboutUs;
    private javax.swing.JPanel jPanelBubur1;
    private javax.swing.JPanel jPanelBubur2;
    private javax.swing.JPanel jPanelBubur3;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelKeranjang1;
    private javax.swing.JPanel jPanelKeranjang2;
    private javax.swing.JPanel jPanelKeranjang3;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMainIcon;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelNavBar;
    private javax.swing.JPanel jPanelOrder;
    private javax.swing.JPanel jPanelToLogin;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerBubur1;
    private javax.swing.JSpinner jSpinnerBubur2;
    private javax.swing.JSpinner jSpinnerBubur3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tabelOrder;
    private javax.swing.JTextArea tfOrderAlamat;
    private javax.swing.JTextField tfOrderFullname;
    private javax.swing.JTextField tfOrderNoTelp;
    // End of variables declaration//GEN-END:variables

}
